<?xml version="1.0" ?>
<robot
    xmlns:xacro="http://ros.org/wiki/xacro">
    <xacro:include filename="$(find robotont_description)/urdf/roller.urdf.xacro"/>
    <!-- Roller positioning -->
    <xacro:property name="roller_radial_dist" value="0.0275" />
    <xacro:property name="roller_z_distance" value="0.008" />
    <xacro:property name="roller_init_angle" value="0" />
    <xacro:macro name="rim_macro" params="name color angle wheel_distance wheel_center_height prefix">
        <link name="${prefix}rim_${name}_link">
            <visual>
                <geometry>
                    <mesh filename="package://robotont_description/meshes/rim.stl"/>
                </geometry>
                <material name="rim_${name}_material">
                    <color rgba="${color} 1"/>
                </material>
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="0.035" length="0.03"/>
                </geometry>
            </collision>
            <inertial>
                <origin xyz="0 0 0"/>
                <mass value="0.00835758"/>
                <inertia
                    ixx="6.63684e-07"
                    ixy="0"
                    ixz="0"
                    iyy="6.63684e-07"
                    iyz="0"
                    izz="9.40333e-07"
                />
            </inertial>
        </link>

        <joint name="${prefix}rim_${name}_joint" type="continuous">
            <parent link="${prefix}base_link" />
            <child link="${prefix}rim_${name}_link" />
            <axis xyz="0 0 1"/>
            <origin
                xyz="${wheel_distance*sin(angle)} ${-wheel_distance*cos(angle)} ${wheel_center_height}"
                rpy="${pi/2} 0 ${angle+pi}"
            />
        </joint>

        <!-- Front rollers -->
        <xacro:roller_macro
            parent="${name}"
            radial_dist="${roller_radial_dist}"
            z_distance="${roller_z_distance}"
            z_distance_reflect="-1"
            init_angle="${roller_init_angle}"
            no_of_roller="0"
            prefix="${prefix}"
        />
        <xacro:roller_macro
            parent="${name}"
            radial_dist="${roller_radial_dist}"
            z_distance="${roller_z_distance}"
            z_distance_reflect="-1"
            init_angle="${roller_init_angle}"
            no_of_roller="1"
            prefix="${prefix}"
        />
        <xacro:roller_macro
            parent="${name}"
            radial_dist="${roller_radial_dist}"
            z_distance="${roller_z_distance}"
            z_distance_reflect="-1"
            init_angle="${roller_init_angle}"
            no_of_roller="2"
            prefix="${prefix}"
        />
        <xacro:roller_macro
            parent="${name}"
            radial_dist="${roller_radial_dist}"
            z_distance="${roller_z_distance}"
            z_distance_reflect="-1"
            init_angle="${roller_init_angle}"
            no_of_roller="3"
            prefix="${prefix}"
        />
        <xacro:roller_macro
            parent="${name}"
            radial_dist="${roller_radial_dist}"
            z_distance="${roller_z_distance}"
            z_distance_reflect="-1"
            init_angle="${roller_init_angle}"
            no_of_roller="4"
            prefix="${prefix}"
        />
        <xacro:roller_macro
            parent="${name}"
            radial_dist="${roller_radial_dist}"
            z_distance="${roller_z_distance}"
            z_distance_reflect="-1"
            init_angle="${roller_init_angle}"
            no_of_roller="5"
            prefix="${prefix}"
        />
        <xacro:roller_macro
            parent="${name}"
            radial_dist="${roller_radial_dist}"
            z_distance="${roller_z_distance}"
            z_distance_reflect="-1"
            init_angle="${roller_init_angle}"
            no_of_roller="6"
            prefix="${prefix}"
        />
        <!-- Back rollers -->
        <xacro:roller_macro
            parent="${name}"
            radial_dist="${roller_radial_dist}"
            z_distance="${roller_z_distance}"
            z_distance_reflect="1"
            init_angle="${roller_init_angle}"
            no_of_roller="0"
            prefix="${prefix}"
        />
        <xacro:roller_macro
            parent="${name}"
            radial_dist="${roller_radial_dist}"
            z_distance="${roller_z_distance}"
            z_distance_reflect="1"
            init_angle="${roller_init_angle}"
            no_of_roller="1"
            prefix="${prefix}"
        />
        <xacro:roller_macro
            parent="${name}"
            radial_dist="${roller_radial_dist}"
            z_distance="${roller_z_distance}"
            z_distance_reflect="1"
            init_angle="${roller_init_angle}"
            no_of_roller="2"
            prefix="${prefix}"
        />
        <xacro:roller_macro
            parent="${name}"
            radial_dist="${roller_radial_dist}"
            z_distance="${roller_z_distance}"
            z_distance_reflect="1"
            init_angle="${roller_init_angle}"
            no_of_roller="3"
            prefix="${prefix}"
        />
        <xacro:roller_macro
            parent="${name}"
            radial_dist="${roller_radial_dist}"
            z_distance="${roller_z_distance}"
            z_distance_reflect="1"
            init_angle="${roller_init_angle}"
            no_of_roller="4"
            prefix="${prefix}"
        />
        <xacro:roller_macro
            parent="${name}"
            radial_dist="${roller_radial_dist}"
            z_distance="${roller_z_distance}"
            z_distance_reflect="1"
            init_angle="${roller_init_angle}"
            no_of_roller="5"
            prefix="${prefix}"
        />
        <xacro:roller_macro
            parent="${name}"
            radial_dist="${roller_radial_dist}"
            z_distance="${roller_z_distance}"
            z_distance_reflect="1"
            init_angle="${roller_init_angle}"
            no_of_roller="6"
            prefix="${prefix}"
        />
        <!-- <transmission name="rim_${name}_transmission"><type>transmission_interface/SimpleTransmission</type><joint name="rim_${name}_joint"><hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface></joint><actuator name="rim_${name}_motor"><mechanicalReduction>1</mechanicalReduction></actuator></transmission> -->
    </xacro:macro>
</robot>
